export class VertriebEinkaufListModel {
  constructor(
    public kalender_id?: number,
    public produktname?: string,
    public beschreibung?: string,
    public datum_von?: string,
    public datum_bis?: string,
    public kalendar_art?: string,
    public prodprod_id?: number,
    public prodspiel_id?: number,
    public prodwerk_id?: number,
    public abko_termin_id?: number,
    public termin_art?: number,
    public termin_typ?: number,
    public anba_id?: number,
    public veranstalter_benutzer?: boolean,
    public created_benutzer_id?: number,
    public created_benutzer_Name?: string,
    public anbieter_betrieb_id?: number,
    public anbieter_betrieb_betriebsname?: string,
    public anbieter_betrieb_strasse?: string,
    public anbieter_betrieb_plz?: string,
    public anbieter_betrieb_stadt?: string,
    public veranstalter_betrieb_id?: number,
    public veranstalter_betrieb_betriebsname?: string,
    public veranstalter_betrieb_strasse?: string,
    public veranstalter_betrieb_plz?: string,
    public veranstalter_betrieb_stadt?: string,
    public spielss_id?: number,
    public spiels_name?: string,
    public Spielort_PLZ?: string,
    public Spielort_Stadt?: string,
    public veranstaltungskategorie_id?: string,
    public anbieter_betrieb_email?: string,
    public veranstalter_betrieb_email?: string,
    public veranstalter_betrieb_telefon?: string,
    public anbieter_betrieb_telefon?: string,
    public vertrag_status?: number,
    public buch_id?: number,
  ) {}
}
